name: edsml-rs
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc=1.21.6
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cftime=1.6.4
  - hdf4=4.2.15
  - hdf5=1.14.4
  - intel-openmp=2024.2.1
  - krb5=1.21.3
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libffi=3.4.2
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnetcdf=4.9.2
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mkl=2024.2.2
  - netcdf4=1.7.2
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.10.16
  - python_abi=3.10
  - setuptools=75.8.0
  - snappy=1.2.1
  - tbb=2021.13.0
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      -r requirements.txt
